import os
from pathlib import Path

from database.connection import connect_database, get_database_backend


POSTGRESQL_SCHEMA = (
    """
    CREATE TABLE IF NOT EXISTS users (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS items (
        item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users (user_id),
        title TEXT NOT NULL,
        description TEXT NOT NULL,
        category TEXT NOT NULL,
        report_type TEXT NOT NULL,
        location TEXT NOT NULL,
        date_lost_found DATE NOT NULL,
        verification_question TEXT,
        status TEXT NOT NULL DEFAULT 'OPEN',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS claims (
        claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_id BIGINT NOT NULL REFERENCES items (item_id),
        claimant_id BIGINT NOT NULL REFERENCES users (user_id),
        verification_answer TEXT NOT NULL,
        additional_message TEXT,
        return_instructions TEXT,
        lost_item_id BIGINT REFERENCES items (item_id),
        claim_status TEXT NOT NULL DEFAULT 'PENDING',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        reviewed_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS messages (
        message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        claim_id BIGINT NOT NULL REFERENCES claims (claim_id),
        sender_id BIGINT NOT NULL REFERENCES users (user_id),
        message_text TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        read_at TIMESTAMP
    )
    """,
)


def initialize_postgresql_database(database_url):
    connection = connect_database(Path('campusclaim.db'), database_url)
    try:
        for statement in POSTGRESQL_SCHEMA:
            connection.execute(statement)
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def initialize_database():
    database_url = os.environ.get('DATABASE_URL')
    if get_database_backend(database_url) == 'postgresql':
        initialize_postgresql_database(database_url)
        return

    from database.init_db import initialize_database as initialize_sqlite_database
    from database.migrate_add_lost_item_id import migrate_database as migrate_lost_item_id
    from database.migrate_add_messages import migrate_database as migrate_messages
    from database.migrate_add_return_instructions import migrate_database as migrate_return_instructions

    initialize_sqlite_database()
    migrate_return_instructions()
    migrate_lost_item_id()
    migrate_messages()


if __name__ == '__main__':
    initialize_database()